const toMethods = require('../utils/toMethods');

module.exports = toMethods({
	defaultScope: 'object',
	scopes: 'object',
	omitNull: 'boolean',
	timestamps: 'boolean',
	paranoid: 'boolean',
	underscored: 'boolean',
	hasTrigger: 'boolean',
	freezeTableName: 'boolean',
	name: 'object',
	modelName: 'string',
	indexes: 'array',
	createdAt: ['string', 'boolean'],
	deletedAt: ['string', 'boolean'],
	updatedAt: ['string', 'boolean'],
	tableName: 'string',
	schema: 'string',
	engine: 'string',
	charset: 'string',
	comment: 'string',
	collate: 'string',
	initialAutoIncrement: 'string',
	hooks: 'object',
	validate: 'object',
	setterMethods: 'object',
	getterMethods: 'object',
	version: ['string', 'boolean'],
});